apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: aether-backend-testing

namespace: aether-testing

resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml

patchesStrategicMerge:
  - config-patch.yaml
  - secret-patch.yaml
  - deployment-patch.yaml

commonLabels:
  environment: testing

images:
  - name: aether-backend
    newTag: testing