apiVersion: v1
kind: ConfigMap
metadata:
  name: aether-config
data:
  gin-mode: "release"
  neo4j-uri: "bolt://neo4j.aether-production.svc.cluster.local:7687"
  keycloak-url: "https://keycloak.aether.com"
  redis-addr: "redis.aether-production.svc.cluster.local:6379"
  kafka-brokers: "kafka.aether-production.svc.cluster.local:9092"
  s3-endpoint: "https://s3.aether.com"
  log-level: "warn"