apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aether-be

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- neo4j.yaml
- neo4j-certificate.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

commonLabels:
  app.kubernetes.io/name: aether-backend
  app.kubernetes.io/component: api
  app.kubernetes.io/part-of: aether

images:
- name: aether-be
  newName: registry-api.tas.scharber.com/aether-be
  newTag: latest
