apiVersion: v1
kind: ConfigMap
metadata:
  name: aether-config
data:
  gin-mode: "debug"
  neo4j-uri: "bolt://neo4j.aether-dev.svc.cluster.local:7687"
  keycloak-url: "http://keycloak.aether-dev.svc.cluster.local:8080"
  redis-addr: "redis.aether-dev.svc.cluster.local:6379"
  kafka-brokers: "kafka.aether-dev.svc.cluster.local:9092"
  s3-endpoint: "http://minio.aether-dev.svc.cluster.local:9000"
  log-level: "debug"